name: Discussion
description: Start a general discussion
labels: ["discussion"]
body:
  - type: markdown
    attributes:
      value: |
        This form should be used for general discussions. To propose a taxonomic change (new name), see the [Taxonomic Proposal form](https://github.com/pteridogroup/ppg-demo/issues/new?assignees=&labels=taxonomic+proposal&template=taxonomic-proposal.yml).
  - type: textarea
    id: discussion
    attributes:
      label: Discussion topic
      description: What do you want to talk about?
    validations:
      required: true